apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafui
  labels:
    app: kafui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-kafui #name of deployed kafka service
  template:
    metadata:
      labels:
        app: kafka-kafui
    spec:
      containers:
      - name: kafui
        image: provectuslabs/kafka-ui:latest
        ports:
          - containerPort: 8080
        env:
          - name: DYNAMIC_CONFIG_ENABLED
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafui
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: kafui
  selector:
    app: kafka-kafui #name of deployed kafka service
  type: LoadBalancer
